// Stub of :
let PokemonType =
{
    "-1": "None",
    0: "Normal",
    1: "Fire",
    2: "Water",
    3: "Electric",
    4: "Grass",
    5: "Ice",
    6: "Fighting",
    7: "Poison",
    8: "Ground",
    9: "Flying",
    10: "Psychic",
    11: "Bug",
    12: "Rock",
    13: "Ghost",
    14: "Dragon",
    15: "Dark",
    16: "Steel",
    17: "Fairy",
    Bug: 11,
    Dark: 15,
    Dragon: 14,
    Electric: 3,
    Fairy: 17,
    Fighting: 6,
    Fire: 1,
    Flying: 9,
    Ghost: 13,
    Grass: 4,
    Ground: 8,
    Ice: 5,
    None: -1,
    Normal: 0,
    Poison: 7,
    Psychic: 10,
    Rock: 12,
    Steel: 16,
    Water: 2
};
